# What are tensors?
Tensors are the building blocks of machine learning. They are multi-dimensional arrays of numbers. Tensors are used to represent data in machine learning. Tensors are used to represent data in machine learning. Tensors are used to represent data in machine learning. Tensors are used to represent data in machine learning.

1-D tensors are also known as vector. The dimension of a vector are number of elements inside it.

Dimension of a tensor is also known as it's rank.

In [4]:
import numpy as np

a = np.array(4) # 0-dim tensor
print(a)
print(a.ndim)

b = np.array([1, 2, 3]) # 1-dim tensor (3-dim vector)
print(b)
print(b.ndim)

c = np.array([[1, 2], [3, 4]]) # 2-dim tensor
print(c)
print(c.ndim)

d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3-dim tensor
print(d)
print(d.ndim)

e = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]) # 4-dim tensor
print(e)
print(e.ndim)

f = np.array([[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]]) # 5-dim tensor
print(f)
print(f.ndim)

print("\n")
print("Shape of a: ", a.shape)
print("Shape of b: ", b.shape)
print("Shape of c: ", c.shape)
print("Shape of d: ", d.shape)
print("Shape of e: ", e.shape)
print("Shape of f: ", f.shape)


4
0
[1 2 3]
1
[[1 2]
 [3 4]]
2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4
[[[[[ 1  2]
    [ 3  4]]

   [[ 5  6]
    [ 7  8]]]


  [[[ 9 10]
    [11 12]]

   [[13 14]
    [15 16]]]]]
5


Shape of a:  ()
Shape of b:  (3,)
Shape of c:  (2, 2)
Shape of d:  (2, 2, 2)
Shape of e:  (2, 2, 2, 2)
Shape of f:  (1, 2, 2, 2, 2)


# Practical Example of Tensors

## 1-D Tensor
If we consider a simple dataset, a single row of data can be represented as a 1-D tensor.

Let's consider a dataset of 5 students and their marks in 3 subjects.

In that for a single student, the data would look like, [70, 80, 90]

## 2-D Tensor
2-D Tensors are collection of 1-D tensors.

Let's consider the same dataset of 5 students and their marks in 3 subjects.

In that for a single student, the data would look like, [70, 80, 90]

And for all 5 students, the data would look like,

[70, 80, 90]
[60, 70, 80]
[50, 60, 70]
[40, 50, 60]
[30, 40, 50]

This is a 2-D tensor.

## 3-D Tensor
3-D tensors are collection of 2-D tensors and are used widely in NLP.
For example if we have three sentences:
Hi Malay
Hi Rahul
Hi Ankit

Now, we first pick out the words and represent each word with a vecotr. In NLP this is called vectorization.

Hi = 1000
Malay = 0100
Rahul = 0010
Ankit = 0001

Now the scentences would look like,

Hi Malay = [1000, 0100]
Hi Rahul = [1000, 0010]
Hi Ankit = [1000, 0001]

In the form of a 3-D tensor, it would look like,

[[[1000, 0100]],
[[1000, 0010]],
[[1000, 0001]]]

## 4-D Tensor
The best example of 4-D tensor is image based data.

## 5-D Tensor
The best example of 5-D tensor is video based data.